name: TypingPlayers
main: dev.gamer153.typingplayers.TypingPlayers
version: 0.0.1
authors: [Gamer153]
api-version: 1.17

commands:
  typing:
    description: Get typing players.
    permission: typingplayers.typing
    usage: /typing

permissions:
  typingplayers.typing:
    description: Use /typing
    default: op
  typingplayers.broadcast:
    description: Receive typing player broadcasts
    default: false
    children:
      - typingplayers.broadcast.start
      - typingplayers.broadcast.stop
  typingplayers.broadcast.start:
    default: false
  typingplayers.broadcast.stop:
    default: false

depend:
  - ProtocolLib

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.0
